export const petData = [
    {
        id: 1,
        age:'11 months',
        shelter:"SPCA",
        breed:'Australian Shepherd',
        description:'Meet sweet Leo! This guy is an energetic and charismatic Australian Shepherd with a long journey ahead of him! He has the most luxurious fur and the happiest little face. He loves to play and would make an excellent adventure buddy when he is all healed from his hip surgeries. He would do best in a home as the only dog or with a very confident and quiet resident dog – a slow introduction would be necessary – information will be given to you on how to do this.  When Leo came into our care we noticed that he had an odd gait, and upon further investigation we discovered that this tail-less wonder needs surgery on both of his hips. This kind of surgery comes with a months-long healing and rehab process, and he will need to be on exercise restriction for quite a while following his operation. He has had one hip done already and we are waiting for that to heal up so that we can perform surgery on the other hip.  As an active dog, Leo has been a bit frustrated at his reduction in exercise. He will need to be crated while you are not at home so he does not get into any chewing mischief. Puzzle toys, kongs and gentle human and/or dog play will go a long way to keeping this adorable boy out of trouble.  We are currently seeking a foster to adopt for Leo where he can relax and heal in peace. We will be sending him into his foster to adopt home with all the things he will need for his recovery.  Please come into the shelter during visiting hours if you would like to meet me. You can also submit an application online if I am in foster or you would like to save some time when you come visit. While we do welcome online applications, in person meets have top priority.',
        image:'dog-images/dog1.jpeg',
        name:"Leo",
        location: 'Vancouver',
        size: "Medium",
        species: "Dog",
        sex: "Male",
        link: "https://spca.bc.ca/adoption/how-to-adopt/"
        
    },
    {
        id: 2,
        age:'2 years old',
        shelter:"SPCA",
        breed:'Chow Chow',
        description:'Meet Hatchi, a stunning 2-year-old male Chow Chow who is on the lookout for his furEVER adult only home. With a history of a couple of homes, including one where he had to be re-homed due to a new baby, Hatchi is now ready to settle into a loving and understanding environment. This distinguished gentleman is best suited for a dog-experienced home with no other pets. He needs a quieter environment in a house with a yard. No downtown/condo living for this boy.  Hatchi may not be as exuberant as some dogs, but he still enjoys an active lifestyle and will thrive in a home that can meet his needs for both physical and mental stimulation. Known for his cleanliness, Hatchi will require regular brushing and grooming to maintain his beautiful coat.',
        image:'dog-images/dog2.jpeg',
        name:"Hatchi",
        location: 'Burnaby',
        size: "Large",
        species: "Dog",
        sex: "Male",
        link: "https://spca.bc.ca/adoption/how-to-adopt/"
        

    },
    {
        id: 3,
        age:'8 months',
        shelter:"SPCA",
        breed:'Coonhound',
        description:'Daffy is a young Coonhound in training. She needs a very experienced family home(older children OK). At this time she needs to continue to work on her manners as can get mouthy and jumpy. She is an absolutely sweetheart with her humans and wants to be around them always. Sadly, a good Samaritan witnessed Daffy come out from the bushes in one of the local Burnaby Parks. She seemed like she may have been homeless for awhile due to some lacerations on her legs. She was immediately taken to a vet clinic to see to the injuries. Through it all she remained friendly and affectionate. Daffy has a story to tell and is very vocal with her constant baying. Being a hound dog, her nose is always to the ground searching mainly for food. She is such a high energy excitable girl, that her new owners need to match her activity level. Keeping her busy, is the key to keeping her happy. Activities like scent work games, agility and regular trips to the dog park where she can explore and use her nose. Daffy enjoys the company of other dogs but slow and proper introductions are recommended. She does not live well with cats and will need an adult only or older children only home.',
        image:'dog-images/dog3.jpeg',
        name:"Daffy",
        location: 'Burnaby',
        size: "Small",
        species: "Dog",
        sex: "Female",
        link: "https://spca.bc.ca/adoption/how-to-adopt/"
    },
    {
        id: 4,
        age:'7 months',
        shelter:"SPCA",
        breed:'Border Collie',
        description:'Say hello to Josiah!  With a friendly demeanor and a high level of intelligence Josiah has stolen our hearts!  This guy came to us from a loving home, along with 7 of his siblings! Although he is one of the more confident of the litter, he is fearful around children, and can be a bit timid when meeting new people, but once you’ve gained his trust, all he wants to do is love, and be loved in return.  He loves learning, and already has some basic training, walks well on leash, knows his name, and is house trained (mostly).  Josiah would thrive in a home with plenty of space, ideally on an acreage, away from the hustle and bustle of city life. He loves to play with toys in the yard, and go for walks, making him an excellent companion for an active household, that will provide the necessary mental, and physical stimulation his breed requires to stay healthy, and happy!  If you think Josiah could be your bosom buddy, please submit an application to the Kamloops branch through the link below!',
        image:'dog-images/dog4.jpeg',
        name:"Josiah",
        location: 'Kamloops',
        size: "Medium",
        species: "Dog",
        sex: "Male",
        link: "https://spca.bc.ca/adoption/how-to-adopt/"
    },
    {
        id: 5,
        age:'1 year old',
        shelter:"SPCA",
        breed:'Husky',
        description:'Meet Blue – Your New Adventure Buddy and Cuddle King!  Ready to meet the coolest dog in town? Blue is a 1-year-old Husky who’s got the looks (those blue eyes!) and the charm to win over your heart. This guy is a total goofball with a serious love for life and a never-ending supply of energy! If you’re looking for a dog who’s always up for an adventure, then Blue might just be your new BFF.  Blue isn’t your average couch potato pup. Nope, he’s got way too much love for toys, zoomies, and outdoor adventures to sit still for long. He’s an absolute blast to be around, especially if you’re into hiking, running, or just need someone to chase frisbees in the yard with. He’s also a social butterfly – great with other dogs and always happy to meet new people (because, in his mind, everyone is a potential new best friend!).  After all the action, though, Blue has a soft side. He’s a snuggler at heart and will happily curl up with you after a fun-filled day. But don’t be fooled – as soon as he sees one of his beloved toys, he’s back in action!',
        image:'dog-images/dog5.jpeg',
        name:"Blue",
        location: 'Quesnel',
        size: "Large",
        species: "Dog",
        sex: "Male",
        link: "https://spca.bc.ca/adoption/how-to-adopt/"
    },
    {
        id: 6,
        age:'Young',
        shelter:"petfinder",
        breed:'Pit Bull Terrier',
        description:'Meet Nikita - the stunning pitty girl who was surrendered to RAPS. Nikita is a high energy, bubbly, sassy and sweet girl. She absolutely loves being the centre of attention and getting all the cuddles & kisses from her human friends. Nikita also loves playing with toys - tug of war is one of her favourite games to play.',
        image:'dog-images/dog6.jpeg',
        name:"Nikita",
        location: 'Richmond',
        size: "Large",
        species: "Dog",
        sex: "Female",
        link: "https://www.petfinder.com/"

    },
    {
        id: 7,
        age:'5 months',
        shelter:"SPCA",
        breed:"Domestic short hair / Siamese",
        description: "Sully only has good days and he will sure try his hardest to make sure your day is just as good as his. This cuddle bug is always happy to see people and you will find that you have to set boundaries with him as you cannot cuddle 24/7! He has done a wonderful job of making his newest little cat friend, Dr. Quinn, come out of her shell and be more open about being around the humans. This beautiful bonded pair would be a great addition to any home that would enjoy having the ying/yang personalities of these two cats around. If you are looking for a quiet little kitty cat, this is not the cat for you.  Please come into the shelter during visiting hours if you would like to meet me. You can also submit an application online if I am in foster or you would like to save some time when you come visit. While we do welcome online applications, in person meets have top priority.",
        image:'cat-images/cat1.jpeg',
        name:"Sully",
        location: 'Vancouver',
        size: "Small",
        species: "Cat",
        sex: "Male",
        link: "https://spca.bc.ca/adoption/how-to-adopt/"
    },
    {
        id: 8,
        age:'3 months',
        shelter:"SPCA",
        breed:"Domestic short hair",
        description: "Meet Kale,  Kale and his sister Mizuna are very special. They came into care with a condition called “Cerebellar Hypoplasia” or Wobbly Cat Syndrome. Kittens with CH require a great deal of attention, care and patience in training. They require a safe space where little hazards are present to keep them from hurting themselves. They would do best in a space without stairs, and with guardians who are home throughout the day to ensure they are keeping out of trouble. They would be best suited to an adult oriented, indoor only home.",
        image:'cat-images/cat5.jpeg',
        name:"Kale",
        location: 'Victoria',
        size: "Small",
        species: "Cat",
        sex: "Male",
        link: "https://spca.bc.ca/adoption/how-to-adopt/"
    },
    {
        id: 9,
        age:'3 years old',
        shelter:"SPCA",
        breed:"Domestic short hair",
        description: "Meet French Fry, an endearing black and white female cat with a heart full of affection and a personality that’s as unique as her name. Though she may be shy at first, French Fry’s gentle nature and soft purrs quickly reveal a deep well of love and warmth. She thrives in serene environments and is best suited for a quiet home without children, where she can feel safe and gradually come out of her shell. With a little patience and a lot of love, French Fry will blossom into a loyal and cherished companion, bringing a touch of sweetness to your life every day.  We don’t know much about her past, but she spent a lot of time outdoors with no home to call her own. Luckily, she was able to survive by the kindness of strangers leaving out food for her and eventually she was brought to the shelter where she is currently hoping to find a place where she can be inside, safe and warm all the time. French Fry came in with broken teeth and will need them removed. She is not yet ready to go home for good until her surgery is complete.",
        image:'cat-images/cat6.jpeg',
        name:"French Fry",
        location: 'Maple Ridge',
        size: "Small",
        species: "Cat",
        sex: "Female",
        link: "https://spca.bc.ca/adoption/how-to-adopt/"
    },
    {
        id: 10,
        age:'4 years old',
        shelter:"SPCA",
        breed:"Domestic short hair",
        description: "Dumpling is an adorable kitty who arrived as a stray, and now she’s searching for her forever home. Just like the tasty treat she’s named after, Dumpling is sweet, a bit round, and utterly irresistible! She’s the boss of the love sessions-when she’s ready for affection, she’ll come to you, but don’t be surprised if she decides she’s had enough and retreats to her cozy bed. Understanding her body language will be key in continuing a happy relationship with this girl! She loves pats and scritches on her head only;)  Her perfect day includes head pets and lounging beside her human, just like a dumpling tucked away in a warm steamer. Dumpling has a fondness for food, which has left her with a little extra fluff, so some meal monitoring will help keep her as cute as ever.  Dumpling would do best in a home without young children, or other pets, where she can be the star of the show. If you’re looking for a loving, independent companion who’s as delightful as her name, Dumpling is ready to be the purrfect little morsel in your life!",
        image:'cat-images/cat3.jpeg',
        name:"Dumpling",
        location: 'Sechelt',
        size: "Small",
        species: "Cat",
        sex: "Female",
        link: "https://spca.bc.ca/adoption/how-to-adopt/"
    },
    {
        id: 11,
        age:'3 months old',
        shelter:"SPCA",
        breed:"Domestic long hair",
        description: "Meet Nebula, a sweet and snuggly kitten who’s ready to fill your home with love and joy! This affectionate little one adores cuddling up for cozy naps and has a blast chasing toys around. Nebula also enjoys the company of other cats, making her a great addition to a multi-pet household. If you’re looking for a playful and loving companion who gets along well with others, Nebula is the perfect furry friend for you!",
        image:'cat-images/cat4.jpeg',
        name:"Nebula",
        location: 'Sechelt',
        size: "Small",
        species: "Cat",
        sex: "Female",
        link: "https://spca.bc.ca/adoption/how-to-adopt/"
    },
    {
        id: 12,
        age:'2 years old',
        shelter:"SPCA",
        breed:"Domestic Medium Hair",
        description: "Marmalade is a sweet, shy kitty looking for a quiet, loving home where she can blossom at her own pace. While she may be timid at first, with patience and gentle affection, Marmalade will show you her loving side. This girl is ready to leave her past behind and find a forever family who will give her the love and security she deserves. Marmalade is bonded to Toast, and they would love to find a calm, safe home together. Marmalade would do best in an environment where she can feel secure and comfortable. Could you be the one to help her come out of her shell?",
        image:'cat-images/cat2.jpeg',
        name:"Marmalade",
        location: 'Richmond',
        size: "Small",
        species: "Cat",
        sex: "Female",
        link: "https://spca.bc.ca/adoption/how-to-adopt/"
    }

]
